name: check
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'zensical.toml'
      - 'requirements.txt'
      - 'docs/**'
      - 'includes/**'
      - 'overrides/**'
permissions:
  contents: read
concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.x
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Site
        run: zensical build --clean
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: super-linter/super-linter/slim@v9
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_TOML: true
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  spelling:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Install Codespell
        run: pip install codespell
      - name: Check Spelling
        run: codespell docs/ --skip="docs/_static/*" --ignore-words-list="namd"
